<?php
if (function_exists('acf_add_local_field_group')) :

  acf_add_local_field_group(array(
    'key' => 'group_5fca3764dc8b1',
    'title' => 'Kontaktformulär',
    'fields' => array(
      array(
        'key' => 'field_5fca376f63128',
        'label' => 'Kontaktformulär',
        'name' => 'kontaktformular',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layouts' => array(
          'layout_5fca389bf795b' => array(
            'key' => 'layout_5fca389bf795b',
            'name' => 'radioknappar',
            'label' => 'Radioknappar',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5fca38a6f795c',
                'label' => 'Etikett',
                'name' => 'etikett',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_5fca38dcf795d',
                'label' => 'Radioknappar',
                'name' => 'radioknappar',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Lägg till radioknapp',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5fca390bf795e',
                    'label' => 'Knappetikett',
                    'name' => 'knappetikett',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5fca37c7c3664' => array(
            'key' => '5fca37c7c3664',
            'name' => 'textfalt',
            'label' => 'Textfält',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5fca37e763129',
                'label' => 'Etikett',
                'name' => 'etikett',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_5fca3a8a49a4f' => array(
            'key' => 'layout_5fca3a8a49a4f',
            'name' => 'textarea',
            'label' => 'Textarea',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5fca3a9449a50',
                'label' => 'Etikett',
                'name' => 'etikett',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_5fca3ac149a51' => array(
            'key' => 'layout_5fca3ac149a51',
            'name' => 'knapp',
            'label' => 'Knapp',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5fca3aca49a52',
                'label' => 'Etikett',
                'name' => 'etikett',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
            'min' => '',
            'max' => '1',
          ),
        ),
        'button_label' => 'Lägg till etikett',
        'min' => '',
        'max' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'kontaktformular',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

endif;
